### ISSUE TITLE
Cannot setup without pytz

### ISSUE THREAD

**Issue by vkrizan** [neo4j-drivers/neotime#4]
Commit 66e1859332697ba4a3b34a6b5eb3dbc70921bea6 added pytz which is later imported in `setup.py`. Setting up neotime on system without previously installed pytz fails:

```
  Downloading https://files.pythonhosted.org/packages/ee/e3/55b0cc07ac244da3ce54b1e842afda8fec6785727a29bd2b1dbf7c6c7922/neotime-1.7.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-wtvi520x/neotime/setup.py", line 30, in <module>
        from neotime.meta import package, version
      File "/tmp/pip-build-wtvi520x/neotime/neotime/__init__.py", line 30, in <module>
        from pytz import FixedOffset
    ModuleNotFoundError: No module named 'pytz'
```

Thank you for quick fix.

**Comment by ultra-mk** [comment]
I discovered this issue while installing `neo4j==1.7.1`. Adding `neotime==1.7.2` to my  deps in `setup.py` seems have fixed the issue.

**Comment by Bierbarbar** [comment]
Just identified the error and submitted a pull request hope this helps you.
